spring:
  flyway:
    url: ${FLYWAY_DB_URL:${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=EventixDb;encrypt=true;trustServerCertificate=true}}
    user: ${FLYWAY_DB_USERNAME:${DB_USERNAME:eventix_app}}
    password: ${FLYWAY_DB_PASSWORD:${DB_PASSWORD}}
  jpa:
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false

logging:
  level:
    com.jairomatias.eventix: DEBUG
